chore(deps): automatic version bump to the most recent packages
build: export cache of build dependencies to the current working delevelopments

```
  /nix/store/1yg24id0csjk4nq1a3apimwf8dqisr9d-bash-interactive-5.3p9-man
copying path '/nix/store/1yg24id0csjk4nq1a3apimwf8dqisr9d-bash-interactive-5.3p9-man' from 'https://cache.nixos.org'...
error: unable to open global cache directory '/build/tmp.iN81GFHdcB': AccessDenied
If this location is not writable then consider specifying an alternative with the ZIG_GLOBAL_CACHE_DIR environment variable or the --global-cache-dir option.
```